version: "3.8"
services:
  shorturl:
    build: .
    ports:
      - 80:80
  redis:
    image: redis/redis-stack-server:7.2.0-v9
    restart: unless-stopped
    environment:
      - REDIS_ARGS=--appendonly yes
    volumes:
      - redis-data:/data
volumes:
  redis-data: