version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  redis:
    image: redis/redis-stack:7.2.0-v9
    restart: unless-stopped
    environment:
      - REDIS_ARGS=--appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 8001:8001
volumes:
  redis-data: